import mongoose from 'mongoose';
import bcrypt from 'bcryptjs';

const userSchema = new mongoose.Schema({
  name: {
    type: String,
    required: true,
    trim: true
  },
  username: {
    type: String,
    required: true,
    trim: true,
    lowercase: true
  },
  email: {
    type: String,
    required: true,
    trim: true,
    lowercase: true
  },
  password: {
    type: String,
    required: true
  },
  role: {
    type: String,
    enum: ['Employee', 'HR', 'Admin'],
    required: true,
    default: 'Employee'
  },
  department: {
    type: String,
    required: true,
    trim: true
  },
  phone: {
    type: String,
    trim: true
  },
  aadhaarNumber: {
    type: String,
    trim: true
  },
  guardianName: {
    type: String,
    trim: true
  },
  mobileNumber: {
    type: String,
    trim: true
  },
  guardianMobileNumber: {
    type: String,
    trim: true
  },
  bankName: {
    type: String,
    trim: true
  },
  bankAccountHolderName: {
    type: String,
    trim: true
  },
  bankAccountNumber: {
    type: String,
    trim: true
  },
  bankIfscCode: {
    type: String,
    trim: true,
    uppercase: true
  },
  isActive: {
    type: Boolean,
    default: true
  },
  isFirstLogin: {
    type: Boolean,
    default: true
  },
  lastLogin: {
    type: Date
  },
  /** When false, employee cannot request paid leave or half-day as paid (unpaid only). Default true for existing users. */
  paidLeaveAccess: {
    type: Boolean,
    default: true
  },
  paidLeaveAllocation: {
    type: Number,
    default: 0 // Additional allocation added by admin (starts at 0, added to default)
  },
  paidLeaveLastAllocatedDate: {
    type: Date // Last date when paid leave was allocated
  },
  manualPaidLeaveAdjustment: {
    type: Number,
    default: 0
  },
  manualExtraTimeAdjustment: {
    type: Number,
    default: 0
  },
  manualUnpaidLeaveAdjustment: {
    type: Number,
    default: 0
  },
  manualHalfDayLeaveAdjustment: {
    type: Number,
    default: 0
  },
  joiningDate: {
    type: String, // Employee joining date in dd-mm-yyyy format
    trim: true
  },
  package: {
    type: Number,
    default: 372000 // Annual CTC in INR — 3.72 lakh (monthly salary = package / 12)
  },
  bonds: [{
    type: {
      type: String,
      enum: ['Internship', 'Job', 'Other'],
      required: true
    },
    periodMonths: {
      type: Number,
      required: true,
      min: 1
    },
    startDate: {
      type: String, // Bond start date in dd-mm-yyyy format
      required: true,
      trim: true
    },
    endDate: {
      type: String, // Bond end date in dd-mm-yyyy format (calculated)
      trim: true
    },
    order: {
      type: Number, // Order of bond (1, 2, 3, etc.)
      required: true,
      default: 1
    },
    salary: {
      type: Number, // Monthly salary (Job) or stipend (Internship)
      default: 0
    }
  }],
  salaryBreakdown: [{
    month: {
      type: Number, // 1-12
      required: true
    },
    year: {
      type: Number,
      required: true
    },
    amount: {
      type: Number,
      required: true,
      default: 0
    },
    bondType: {
      type: String,
      enum: ['Internship', 'Job', 'Other'],
      required: true
    },
    startDate: {
      type: String, // dd-mm-yyyy format
      required: true
    },
    endDate: {
      type: String, // dd-mm-yyyy format
      required: true
    },
    isPartialMonth: {
      type: Boolean,
      default: false
    },
    isPaid: {
      type: Boolean,
      default: false
    },
    paidAt: {
      type: Date
    },
    paidBy: {
      type: String // Name of admin/HR who marked it as paid
    }
  }],
  /** Detailed salary slips generated by Admin/HR for employee download */
  salarySlips: [{
    month: { type: Number, required: true },
    year: { type: Number, required: true },
    companyName: { type: String, default: 'KriraAI Pvt. Ltd.' },
    companyAddress: { type: String, default: '' },
    empName: { type: String, default: '' },
    empNo: { type: String, default: '' },
    designation: { type: String, default: '' },
    doj: { type: String, default: '' },
    payDate: { type: String, default: '' },
    pfNo: { type: String, default: 'NA' },
    uan: { type: String, default: 'NA' },
    paidDays: { type: Number, default: 0 },
    lopDays: { type: Number, default: 0 },
    basic: { type: Number, default: 0 },
    ytdBasic: { type: Number, default: 0 },
    fixedAllowance: { type: Number, default: 0 },
    ytdFixedAllowance: { type: Number, default: 0 },
    lopDeduction: { type: Number, default: 0 },
    ytdLopDeduction: { type: Number, default: 0 },
    pTax: { type: Number, default: 0 },
    ytdPTax: { type: Number, default: 0 },
    tds: { type: Number, default: 0 },
    ytdTds: { type: Number, default: 0 },
    savedAt: { type: Date, default: Date.now },
    savedBy: { type: String }
  }],
  lastForwardedMonth: {
    type: String, // e.g. "2026-03"
    trim: true
  },
  forwardedMonths: {
    type: Map,
    of: Number,
    default: {}
  },
  forwardedInMonths: {
    type: Map,
    of: Number,
    default: {}
  },
  /** Employee-specific default check-in (HH:mm). Null/absent = use company default. */
  defaultCheckInTime: {
    type: String,
    default: null
  },
  /** Per-day check-in override for this employee: YYYY-MM-DD → HH:mm */
  checkInTimeOverrides: {
    type: Map,
    of: String,
    default: () => new Map()
  },
  /** Employee-specific default checkout (HH:mm). Null/absent = use company default. */
  defaultCheckoutTime: {
    type: String,
    default: null
  },
  /** Per-day checkout override for this employee: YYYY-MM-DD → HH:mm */
  checkoutTimeOverrides: {
    type: Map,
    of: String,
    default: () => new Map()
  }
}, {
  timestamps: true
});

// Hash password before saving
userSchema.pre('save', async function (next) {
  if (!this.isModified('password')) return next();
  this.password = await bcrypt.hash(this.password, 10);
  next();
});

// Compare password method
userSchema.methods.comparePassword = async function (candidatePassword) {
  return await bcrypt.compare(candidatePassword, this.password);
};

const User = mongoose.model('User', userSchema);

// Function to drop unique indexes on username and email to allow duplicates
export const dropUniqueIndexes = async () => {
  try {
    if (User.collection) {
      const indexes = await User.collection.indexes();
      for (const index of indexes) {
        // Drop unique indexes on username and email
        if (index.name === 'username_1' || index.name === 'email_1' ||
          (index.key && (index.key.username === 1 || index.key.email === 1))) {
          try {
            await User.collection.dropIndex(index.name);
            console.log(`Dropped unique index: ${index.name}`);
          } catch (err) {
            // Index might not exist, ignore error
            if (err.code !== 27) { // 27 = IndexNotFound
              console.log(`Note: Could not drop index ${index.name}`);
            }
          }
        }
      }
    }
  } catch (err) {
    // Ignore errors - indexes might not exist
    console.log('Note: Could not check/drop indexes (this is normal if collection is empty)');
  }
};

export default User;



